[package]
name = "alf"
version = "1.0.1"
authors = ["Toon Spin <toon.spin@gmail.com>"]
edition = "2018"

[dependencies]
memchr = "2"
structopt = {version = "0.3", features = ["wrap_help"]}
atty = "0.2"
